export interface Country {
  code: string;
  name: string;
}

export interface CountryGroup {
  name: string;
  countries: Country[];
}

export const countries = [
  {
    name: 'Europe',
    countries: [
      { code: 'ALA', name: 'Åland Islands' },
      { code: 'ALB', name: 'Albania' },
      { code: 'AND', name: 'Andorra' },
      { code: 'AUT', name: 'Austria' },
      { code: 'BEL', name: 'Belgium' },
      { code: 'BGR', name: 'Bulgaria' },
      { code: 'BIH', name: 'Bosnia and Herzegovina' },
      { code: 'BLR', name: 'Belarus' },
      { code: 'CHE', name: 'Switzerland' },
      { code: 'CZE', name: 'Czechia' },
      { code: 'DEU', name: 'Germany' },
      { code: 'DNK', name: 'Denmark' },
      { code: 'ESP', name: 'Spain' },
      { code: 'EST', name: 'Estonia' },
      { code: 'FIN', name: 'Finland' },
      { code: 'FRA', name: 'France' },
      { code: 'FRO', name: 'Faroe Islands' },
      { code: 'GBR', name: 'United Kingdom' },
      { code: 'GIB', name: 'Gibraltar' },
      { code: 'GRC', name: 'Greece' },
      { code: 'HRV', name: 'Croatia' },
      { code: 'HUN', name: 'Hungary' },
      { code: 'IMN', name: 'Isle of Man' },
      { code: 'IRL', name: 'Ireland' },
      { code: 'ISL', name: 'Iceland' },
      { code: 'ITA', name: 'Italy' },
      { code: 'JEY', name: 'Jersey' },
      { code: 'LIE', name: 'Liechtenstein' },
      { code: 'LTU', name: 'Lithuania' },
      { code: 'LUX', name: 'Luxembourg' },
      { code: 'LVA', name: 'Latvia' },
      { code: 'MCO', name: 'Monaco' },
      { code: 'MDA', name: 'Moldova' },
      { code: 'MKD', name: 'North Macedonia' },
      { code: 'MLT', name: 'Malta' },
      { code: 'MNE', name: 'Montenegro' },
      { code: 'NLD', name: 'Netherlands' },
      { code: 'NOR', name: 'Norway' },
      { code: 'POL', name: 'Poland' },
      { code: 'PRT', name: 'Portugal' },
      { code: 'ROU', name: 'Romania' },
      { code: 'RUS', name: 'Russia' },
      { code: 'SMR', name: 'San Marino' },
      { code: 'SRB', name: 'Serbia' },
      { code: 'SVK', name: 'Slovakia' },
      { code: 'SVN', name: 'Slovenia' },
      { code: 'SWE', name: 'Sweden' },
      { code: 'UKR', name: 'Ukraine' },
      { code: 'VAT', name: 'Vatican City' },
    ],
  },
  {
    name: 'Asia',
    countries: [
      { code: 'AFG', name: 'Afghanistan' },
      { code: 'ARM', name: 'Armenia' },
      { code: 'AZE', name: 'Azerbaijan' },
      { code: 'BHR', name: 'Bahrain' },
      { code: 'BGD', name: 'Bangladesh' },
      { code: 'BTN', name: 'Bhutan' },
      { code: 'BRN', name: 'Brunei Darussalam' },
      { code: 'KAZ', name: 'Kazakhstan' },
      { code: 'CHN', name: 'China' },
      { code: 'CYP', name: 'Cyprus' },
      { code: 'GEO', name: 'Georgia' },
      { code: 'IND', name: 'India' },
      { code: 'IDN', name: 'Indonesia' },
      { code: 'IRN', name: 'Iran' },
      { code: 'IRQ', name: 'Iraq' },
      { code: 'ISR', name: 'Israel' },
      { code: 'JPN', name: 'Japan' },
      { code: 'JOR', name: 'Jordan' },
      { code: 'KOR', name: 'South Korea' },
      { code: 'KWT', name: 'Kuwait' },
      { code: 'KGZ', name: 'Kyrgyzstan' },
      { code: 'LAO', name: 'Laos' },
      { code: 'LBN', name: 'Lebanon' },
      { code: 'MYS', name: 'Malaysia' },
      { code: 'MDV', name: 'Maldives' },
      { code: 'MNG', name: 'Mongolia' },
      { code: 'MMR', name: 'Myanmar' },
      { code: 'NPL', name: 'Nepal' },
      { code: 'OMN', name: 'Oman' },
      { code: 'PAK', name: 'Pakistan' },
      { code: 'PHL', name: 'Philippines' },
      { code: 'QAT', name: 'Qatar' },
      { code: 'SAU', name: 'Saudi Arabia' },
      { code: 'SGP', name: 'Singapore' },
      { code: 'LKA', name: 'Sri Lanka' },
      { code: 'SYR', name: 'Syria' },
      { code: 'TWN', name: 'Taiwan' },
      { code: 'TJK', name: 'Tajikistan' },
      { code: 'THA', name: 'Thailand' },
      { code: 'TLS', name: 'Timor-Leste' },
      { code: 'TUR', name: 'Turkey' },
      { code: 'TKM', name: 'Turkmenistan' },
      { code: 'ARE', name: 'United Arab Emirates' },
      { code: 'UZB', name: 'Uzbekistan' },
      { code: 'VNM', name: 'Vietnam' },
      { code: 'YEM', name: 'Yemen' },
    ],
  },
  {
    name: 'Africa',
    countries: [
      { code: 'DZA', name: 'Algeria' },
      { code: 'AGO', name: 'Angola' },
      { code: 'BEN', name: 'Benin' },
      { code: 'BWA', name: 'Botswana' },
      { code: 'BFA', name: 'Burkina Faso' },
      { code: 'BDI', name: 'Burundi' },
      { code: 'CPV', name: 'Cabo Verde' },
      { code: 'CMR', name: 'Cameroon' },
      { code: 'CAF', name: 'Central African Republic' },
      { code: 'TCD', name: 'Chad' },
      { code: 'COM', name: 'Comoros' },
      { code: 'COG', name: 'Congo' },
      { code: 'COD', name: 'Congo, Democratic Republic' },
      { code: 'CIV', name: "Côte d'Ivoire" },
      { code: 'DJI', name: 'Djibouti' },
      { code: 'EGY', name: 'Egypt' },
      { code: 'GNQ', name: 'Equatorial Guinea' },
      { code: 'ERI', name: 'Eritrea' },
      { code: 'SWZ', name: 'Eswatini' },
      { code: 'ETH', name: 'Ethiopia' },
      { code: 'GAB', name: 'Gabon' },
      { code: 'GMB', name: 'Gambia' },
      { code: 'GHA', name: 'Ghana' },
      { code: 'GIN', name: 'Guinea' },
      { code: 'GNB', name: 'Guinea-Bissau' },
      { code: 'KEN', name: 'Kenya' },
      { code: 'LSO', name: 'Lesotho' },
      { code: 'LBR', name: 'Liberia' },
      { code: 'LBY', name: 'Libya' },
      { code: 'MDG', name: 'Madagascar' },
      { code: 'MWI', name: 'Malawi' },
      { code: 'MLI', name: 'Mali' },
      { code: 'MRT', name: 'Mauritania' },
      { code: 'MUS', name: 'Mauritius' },
      { code: 'MYT', name: 'Mayotte' },
      { code: 'MAR', name: 'Morocco' },
      { code: 'MOZ', name: 'Mozambique' },
      { code: 'NAM', name: 'Namibia' },
      { code: 'NER', name: 'Niger' },
      { code: 'NGA', name: 'Nigeria' },
      { code: 'RWA', name: 'Rwanda' },
      { code: 'STP', name: 'Sao Tome and Principe' },
      { code: 'SEN', name: 'Senegal' },
      { code: 'SYC', name: 'Seychelles' },
      { code: 'SLE', name: 'Sierra Leone' },
      { code: 'SOM', name: 'Somalia' },
      { code: 'ZAF', name: 'South Africa' },
      { code: 'SSD', name: 'South Sudan' },
      { code: 'SDN', name: 'Sudan' },
      { code: 'TZA', name: 'Tanzania' },
      { code: 'TGO', name: 'Togo' },
      { code: 'UGA', name: 'Uganda' },
      { code: 'ZMB', name: 'Zambia' },
      { code: 'ZWE', name: 'Zimbabwe' },
    ],
  },
  {
    name: 'NorthAmerica',
    countries: [
      { code: 'ATG', name: 'Antigua and Barbuda' },
      { code: 'BHS', name: 'Bahamas' },
      { code: 'BRB', name: 'Barbados' },
      { code: 'BLZ', name: 'Belize' },
      { code: 'BMU', name: 'Bermuda' },
      { code: 'CAN', name: 'Canada' },
      { code: 'CRI', name: 'Costa Rica' },
      { code: 'CUB', name: 'Cuba' },
      { code: 'CUW', name: 'Curaçao' },
      { code: 'DMA', name: 'Dominica' },
      { code: 'DOM', name: 'Dominican Republic' },
      { code: 'SLV', name: 'El Salvador' },
      { code: 'GRD', name: 'Grenada' },
      { code: 'GLP', name: 'Guadeloupe' },
      { code: 'GTM', name: 'Guatemala' },
      { code: 'HTI', name: 'Haiti' },
      { code: 'HND', name: 'Honduras' },
      { code: 'JAM', name: 'Jamaica' },
      { code: 'MTQ', name: 'Martinique' },
      { code: 'MEX', name: 'Mexico' },
      { code: 'MSR', name: 'Montserrat' },
      { code: 'NIC', name: 'Nicaragua' },
      { code: 'PAN', name: 'Panama' },
      { code: 'PRI', name: 'Puerto Rico' },
      { code: 'BLM', name: 'Saint Barthélemy' },
      { code: 'KNA', name: 'Saint Kitts and Nevis' },
      { code: 'LCA', name: 'Saint Lucia' },
      { code: 'MAF', name: 'Saint Martin' },
      { code: 'SPM', name: 'Saint Pierre and Miquelon' },
      { code: 'VCT', name: 'Saint Vincent and the Grenadines' },
      { code: 'TTO', name: 'Trinidad and Tobago' },
      { code: 'TCA', name: 'Turks and Caicos Islands' },
      { code: 'USA', name: 'United States' },
      { code: 'VIR', name: 'United States Virgin Islands' },
    ],
  },
  {
    name: 'SouthAmerica',
    countries: [
      { code: 'ARG', name: 'Argentina' },
      { code: 'BOL', name: 'Bolivia' },
      { code: 'BRA', name: 'Brazil' },
      { code: 'CHL', name: 'Chile' },
      { code: 'COL', name: 'Colombia' },
      { code: 'ECU', name: 'Ecuador' },
      { code: 'FLK', name: 'Falkland Islands' },
      { code: 'GUF', name: 'French Guiana' },
      { code: 'GUY', name: 'Guyana' },
      { code: 'PRY', name: 'Paraguay' },
      { code: 'PER', name: 'Peru' },
      { code: 'SUR', name: 'Suriname' },
      { code: 'URY', name: 'Uruguay' },
      { code: 'VEN', name: 'Venezuela' },
    ],
  },
  {
    name: 'Oceania',
    countries: [
      { code: 'ASM', name: 'American Samoa' },
      { code: 'AUS', name: 'Australia' },
      { code: 'COK', name: 'Cook Islands' },
      { code: 'FJI', name: 'Fiji' },
      { code: 'PYF', name: 'French Polynesia' },
      { code: 'GUM', name: 'Guam' },
      { code: 'KIR', name: 'Kiribati' },
      { code: 'MHL', name: 'Marshall Islands' },
      { code: 'FSM', name: 'Micronesia' },
      { code: 'NRU', name: 'Nauru' },
      { code: 'NCL', name: 'New Caledonia' },
      { code: 'NZL', name: 'New Zealand' },
      { code: 'NIU', name: 'Niue' },
      { code: 'NFK', name: 'Norfolk Island' },
      { code: 'MNP', name: 'Northern Mariana Islands' },
      { code: 'PLW', name: 'Palau' },
      { code: 'PNG', name: 'Papua New Guinea' },
      { code: 'PCN', name: 'Pitcairn' },
      { code: 'WSM', name: 'Samoa' },
      { code: 'SLB', name: 'Solomon Islands' },
      { code: 'TKL', name: 'Tokelau' },
      { code: 'TON', name: 'Tonga' },
      { code: 'TUV', name: 'Tuvalu' },
      { code: 'VUT', name: 'Vanuatu' },
      { code: 'WLF', name: 'Wallis and Futuna' },
    ],
  },
  {
    name: 'Antarctica',
    countries: [
      { code: 'BVT', name: 'Bouvet Island' },
      { code: 'HMD', name: 'Heard Island and McDonald Islands' },
    ],
  },
  { name: 'Unknown', countries: [{ code: 'UNKNOWN', name: 'Unknown' }] },
];
